<?php

namespace ErrorsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ErrorRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ErrorRepository extends EntityRepository
{
}
