services:
    schedule_handler:
        class: TaskBundle\Services\ScheduleHandler
        arguments: ['@doctrine.orm.entity_manager', '@api_response_formatter', '@validator']

    period_handler:
        class: TaskBundle\Services\PeriodHandler
        arguments: ['@doctrine.orm.entity_manager', '@api_response_formatter', '@validator', '@schedule_handler']