services:
    schedule_service:
        class: TaskBundle\Services\Schedule
        arguments: ['@doctrine.orm.entity_manager', '@api_response_formatter']

#    schedule.example:
#        class: TaskBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
