services:
    period_handler:
        class: TaskBundle\Services\PeriodHandler
        arguments: ['@doctrine.orm.entity_manager', '@validator']
    task_handler:
        class: TaskBundle\Services\TaskHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'
            - '@base_helper'

    task_entry_handler:
        class: TaskBundle\Services\TaskEntryHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'
            - '@base_helper'

    challenge_handler:
        class: TaskBundle\Services\ChallengeHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'

    outstanding_tasks_source:
        class: TaskBundle\Services\OutstandingTasksSource
        arguments:
            - '@task_entry_handler'
            - '@user_handler'
        tags:
            - 'notification_source'
