services:
    period_handler:
        class: TaskBundle\Services\PeriodHandler
        arguments: ['@doctrine.orm.entity_manager', '@api_response_formatter', '@validator']
    task_handler:
        class: TaskBundle\Services\TaskHandler
        arguments: ['@doctrine.orm.entity_manager', '@api_response_formatter', '@validator']
    task_normalizer:
        class: TaskBundle\Services\TaskNormalizer
        arguments: ['@metadata_factory']
        calls: [[setSerializer, ['@serializer']]]
    period_normalizer:
        class: TaskBundle\Services\PeriodNormalizer
        arguments: ['@metadata_factory']
        calls: [[setSerializer, ['@serializer']]]
