services:
    datetime_handler:
        class: TaskBundle\Service\DateTimeHandler

#    schedule.example:
#        class: TaskBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
