services:
#    store.example:
#        class: StoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  item_handler:
    class: StoreBundle\Services\ItemHandler
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@api_response_formatter'
        - '@validator'