services:
#    store.example:
#        class: StoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  item_handler:
    class: StoreBundle\Services\ItemHandler
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@validator'
        - '@buyitem_handler'

  buyitem_handler:
    class: StoreBundle\Services\BuyItemHandler
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@validator'

  itementry_handler:
    class: StoreBundle\Services\StoreItemHandler
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@validator'

  itemcategory_handler:
    class: StoreBundle\Services\ItemCategoryHandler
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@validator'
  receipt_handler:
    class: StoreBundle\Services\ReceiptHandler
    arguments:
        - '@doctrine.orm.entity_manager'
        - '@validator'
        - '@buyitem_handler'
        - '@item_handler'
        - '@store_http'

  store_http:
    class: StoreBundle\Services\StoreHttp
    arguments:
        - '%receipt_check_username%'
        - '%receipt_check_password%'
