notes:
    resource: "@NotesBundle/Controller/"
    type:     annotation
    prefix:   /notes

base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /

schedule:
    resource: "@ScheduleBundle/Controller/"
    type:     annotation
    prefix:   /schedule

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"