notes:
    resource: "@NotesBundle/Controller/"
    type:     annotation
    prefix:   /notes

base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /

schedule:
    resource: "@TaskBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

schedule_api:
    type: rest
    prefix: /api
    resource: "@TaskBundle/Resources/config/routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc