food:
    resource: "@FoodBundle/Controller/"
    type:     annotation
    prefix:   /

errors:
    resource: "@ErrorsBundle/Controller/"
    type:     annotation
    prefix:   /

note_api:
    type: rest
    prefix: /api
    resource: "@NotesBundle/Resources/config/routes.yml"

base:
    resource: "@BaseBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

task_api:
    type: rest
    prefix: /api
    resource: "@TaskBundle/Resources/config/routes.yml"

errors_api:
    type: rest
    prefix: /api
    resource: "@ErrorsBundle/Resources/config/routes.yml"

users_api:
    type: rest
    prefix: /api
    resource: "@UserBundle/Resources/config/routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc