<?php

namespace TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PeriodRepository extends EntityRepository
{
}
