<?php

namespace TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * TaskEntryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TaskEntryRepository extends EntityRepository
{
    public function getLastUncompleted(array $tasksIds)
    {
        $request = $this->getEntityManager()->getConnection()->prepare(
            'SELECT task_id, id, date
FROM task_entries
WHERE task_entries.task_id IN (:tasksIds) AND task_entries IS NULL
GROUP BY task_entries.task_id LIMIT 1'
        );
        $request->execute(
            [
            ]
        );

        return $request->fetchAll();
    }
}
