<?php

namespace TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * TaskEntryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class TaskEntryRepository extends EntityRepository
{
    /**
     * @param array $tasksIds
     * @param \DateTime $date
     * @return array
     */
    public function getTaskLinesLengths(array $tasksIds, \DateTime $date = null)
    {
        $date = $date ?? new \DateTime('midnight');
        $tasksIdsString = join(',', $tasksIds);
        $request = $this->getEntityManager()->getConnection()->prepare(
            "SELECT
  x.task_id,
  count(*) AS lineLength
FROM task_entries x
  JOIN (SELECT
          task_id,
          MAX(date) AS max_date
        FROM task_entries
        WHERE is_completed = 0 AND date < :date
        GROUP BY task_id) y ON x.task_id = y.task_id
WHERE date > y.max_date AND date < :date AND  y.task_id IN ($tasksIdsString)
GROUP BY x.task_id"
        );
        $request->execute(
            [
                ':date' => $date->format('Y-m-d')
            ]
        );

        return $request->fetchAll();
    }
}
