services:
    listeners_handler:
        class: NotesBundle\Services\ListenersHandler
        arguments: ['@doctrine.orm.entity_manager', '@validator']

    notes_handler:
        class: NotesBundle\Services\NotesHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'