services:
    listeners_handler:
        class: NotesBundle\Services\ListenersHandler
        arguments: ['@doctrine.orm.entity_manager', '@api_response_formatter', '@validator']

    listeners_normalizer:
        class: NotesBundle\Services\ListenersNormalizer
        arguments: ['@object_normalizer']