services:
    food.services.ingredient_normalizer:
        class: FoodBundle\Services\IngredientNormalizer
        arguments: ['@metadata_factory']
    food.services.ingredient_handler:
        class: FoodBundle\Services\IngredientHandler
        arguments: ['@doctrine.orm.entity_manager', '@api_response_formatter', '@validator']
    food.services.dish_handler:
        class: FoodBundle\Services\DishHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@api_response_formatter'
            - '@validator'

    food.services.recipe_handler:
        class: FoodBundle\Services\RecipeHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@api_response_formatter'
            - '@validator'

    food.services.recipe_subscriber:
        class: FoodBundle\EventListener\RecipeSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    food.services.dish_subscriber:
        class: FoodBundle\EventListener\DishSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }