services:
    food.services.ingredient_normalizer:
        class: FoodBundle\Services\IngredientNormalizer
        arguments: ['@object_normalizer']
    food.services.ingredient_handler:
        class: FoodBundle\Services\IngredientHandler
        arguments: ['@doctrine.orm.entity_manager', '@api_response_formatter', '@validator']
    food.services.dish_handler:
        class: FoodBundle\Services\DishHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@api_response_formatter'
            - '@validator'

    food.services.dish_normalizer:
        class: FoodBundle\Services\DishNormalizer
        arguments: ['@object_normalizer']

    food.services.recipe_normalizer:
        class: FoodBundle\Services\RecipeNormalizer
        arguments:
            - '@object_normalizer'
            - '@food.services.dish_normalizer'
            - '@food.services.ingredient_data_normalizer'
    food.services.recipe_handler:
        class: FoodBundle\Services\RecipeHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@api_response_formatter'
            - '@validator'
    food.services.ingredient_data_normalizer:
        class: FoodBundle\Services\IngredientDataNormalizer
        arguments: ['@object_normalizer', '@food.services.ingredient_normalizer']

    food.services.recipe_subscriber:
        class: FoodBundle\EventListener\RecipeSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }