services:
    food.services.ingredient_handler:
        class: FoodBundle\Services\IngredientHandler
        arguments: ['@doctrine.orm.entity_manager', '@validator']
    food.services.dish_handler:
        class: FoodBundle\Services\DishHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'

    food.services.recipe_handler:
        class: FoodBundle\Services\RecipeHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'

    food.services.meal_handler:
        class: FoodBundle\Services\MealHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'
            - '@base_helper'
            - '@task_handler'

    food.services.meal_type_handler:
        class: FoodBundle\Services\MealTypeHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@validator'

    food.services.recipe_subscriber:
        class: FoodBundle\EventListener\RecipeSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    food.services.dish_subscriber:
        class: FoodBundle\EventListener\DishSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }