services:
  api_response_formatter:
    class: BaseBundle\Services\ApiResponseFormatter
    arguments: ['@error_message_handler']

  error_message_handler:
    class: BaseBundle\Models\ErrorMessages
    arguments: ['@monolog.logger', '@translator.default']

  metadata_factory:
    class: Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory
    arguments: ['@annotaion_loader']


  annotaion_loader:
    class: Symfony\Component\Serializer\Mapping\Loader\AnnotationLoader
    arguments: ['@annotations.cached_reader']

  base_helper:
    class: BaseBundle\Services\BaseHelper

  token_handler:
    class: BaseBundle\Services\UserTokenHandler
    arguments: ['@user_handler']