services:
#    base.example:
#        class: BaseBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    api_response_formatter:
      class: BaseBundle\Services\ApiResponseFormatter