services:
  api_response_formatter:
    class: BaseBundle\Services\ApiResponseFormatter
    arguments: ['@error_message_handler']

  error_message_handler:
    class: BaseBundle\Models\ErrorMessages
    arguments: ['@monolog.logger', '@translator.default']

  object_normalizer:
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    arguments: ['@metadata_factory']
    calls:
        - [setSerializer, ['@serializer']]

  metadata_factory:
    class: Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory
    arguments: ['@annotaion_loader']


  annotaion_loader:
    class: Symfony\Component\Serializer\Mapping\Loader\AnnotationLoader
    arguments: ['@annotations.cached_reader']

  base_helper:
    class: BaseBundle\Services\BaseHelper

  encoder: