services:
  api_response_formatter:
    class: BaseBundle\Services\ApiResponseFormatter
    arguments: ['@error_message_handler']

  error_message_handler:
    class: BaseBundle\Models\ErrorMessages
    arguments: ['@monolog.logger', '@translator.default']

  metadata_factory:
    class: Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactory
    arguments: ['@pv.annotation_loader']

  pv.annotation_loader:
    class: BaseBundle\Lib\Serialization\Mapping\Loader\PVAnnotationLoader
    arguments: ['@annotations.cached_reader']

  base_helper:
    class: BaseBundle\Services\BaseHelper

  token_handler:
    class: BaseBundle\Services\UserTokenHandler
    arguments: ['@user_handler']

  pv_normalizer:
    class: BaseBundle\Services\PVNormalizer
    arguments:
      - '@metadata_factory'
      - '@serializer.name_converter.camel_case_to_snake_case'
      - '@property_accessor'
      - '@doctrine.orm.default_entity_manager.property_info_extractor'
      - '@doctrine.orm.entity_manager'
      - '@annotations.reader'
    calls: [[setSerializer, ['@serializer']]]
    tags:
        - { name: serializer.normalizer }

  pv.authentication_subscriber:
    class: BaseBundle\EventListener\AuthenticationSubscriber
    arguments:
        - '@token_handler'
        - '@security.token_storage'
        - '%fos_user.firewall_name%'
    tags:
        - {name: kernel.event_subscriber}
