services:
  api_response_formatter:
    class: BaseBundle\Services\ApiResponseFormatter
    arguments: ['@error_message_handler']

  error_message_handler:
    class: BaseBundle\Models\ErrorMessageHandler
    arguments: ['@monolog.logger']