services:
  user_handler:
    class: UserBundle\Services\UserHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@security.password_encoder'
  achievement_manager:
    class: UserBundle\Services\AchievementManager
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@base_helper'