services:
  user_handler:
    class: UserBundle\Services\UserHandler
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@security.password_encoder'
  user_normalizer:
    class: UserBundle\Services\UserNormalizer
    arguments: ['@object_normalizer']