<?php

namespace StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BuyItemRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BuyItemRepository extends EntityRepository
{
}
