<?php

namespace StoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReceiptRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ReceiptRepository extends EntityRepository
{
    /**
     * @param string $fiscalNumber
     * @param string $fiscalDocNumber
     * @param string $fpd
     * @return null|object|Receipt
     * @throws \Doctrine\ORM\ORMException
     */
    public function findExistingReceipt(string $fiscalNumber, string $fiscalDocNumber, string $fpd)
    {
        return $this
            ->findOneBy([
                'fiscalNumber' => $fiscalNumber,
                'fiscalDocumentNumber' => $fiscalDocNumber,
                'fpd' => $fpd
            ]);
    }
}
